import { describe, expect, it } from 'vitest'
import type { PaletteColor } from '@/domain'
import { ColorNameListNamer } from './colorNameListNamer'

const namer = new ColorNameListNamer()
const custom = (hex: string, rgb: [number, number, number]): PaletteColor => ({
  id: `custom:${hex}`,
  name: 'Custom color',
  hex,
  rgb,
  metadata: { custom: true },
})

describe('ColorNameListNamer', () => {
  it('reports the complete catalog size', () => expect(namer.count).toBe(31_914))

  it('can prepare its lazily loaded catalog', async () => {
    await expect(namer.prepare()).resolves.toBeUndefined()
  })

  it('uses an exact catalog name for an exact custom hex', async () => {
    const named = await namer.name(custom('#abcdef', [171, 205, 239]))
    expect(named).toMatchObject({ id: 'custom:#abcdef', name: 'Alphabet Blue', hex: '#abcdef', rgb: [171, 205, 239] })
  })

  it('includes source and match metadata', async () => {
    const named = await namer.name(custom('#123456', [18, 52, 86]))
    expect(named.metadata).toMatchObject({ custom: true, nameSource: 'Color Name List', nameMatchHex: '#123456', nameDistance: 0 })
  })

  it('finds a perceptually close name when no exact hex exists', async () => {
    const named = await namer.name(custom('#12abef', [18, 171, 239]))
    expect(named.name).not.toBe('Custom color')
    expect(named.hex).toBe('#12abef')
    expect(Number(named.metadata?.nameDistance)).toBeGreaterThan(0)
  })

  it('names colors generated by a recommendation engine', async () => {
    const named = await namer.name({ id: 'generated:1', name: 'Spectrum 1', hex: '#123456', rgb: [18, 52, 86], metadata: { generated: true } })
    expect(named.name).toBe('Incremental Blue')
  })

  it('preserves historical palette names and object identity', async () => {
    const archive: PaletteColor = { id: 'wada:1', name: 'Carmine', hex: '#abcdef', rgb: [171, 205, 239], metadata: { sourceIndex: 1 } }
    await expect(namer.name(archive)).resolves.toBe(archive)
  })

  it('ranks an exact name before names that merely contain it', async () => {
    const results = await namer.search('mauve', 5)
    expect(results[0].name).toBe('Mauve')
    expect(results).toHaveLength(5)
  })

  it('searches names without case or surrounding-space sensitivity', async () => {
    const results = await namer.search('  ALPHABET BLUE  ', 2)
    expect(results[0]).toMatchObject({ name: 'Alphabet Blue', hex: '#abcdef' })
  })

  it('searches accented names with plain ASCII input', async () => {
    const results = await namer.search('zurich blue', 2)
    expect(results.some((color) => color.name === 'Zürich Blue')).toBe(true)
  })

  it('searches by exact hex', async () => {
    const results = await namer.search('#123456', 1)
    expect(results).toEqual([expect.objectContaining({ name: 'Incremental Blue', hex: '#123456' })])
  })

  it('returns catalog results as selectable palette colors', async () => {
    const [result] = await namer.search('Alphabet Blue', 1)
    expect(result).toMatchObject({ id: 'named:#abcdef', rgb: [171, 205, 239], metadata: { named: true, nameSource: 'Color Name List' } })
  })

  it.each([['', 8], ['   ', 8], ['blue', 0], ['blue', -1]] as const)('returns no results for query %j with limit %i', async (query, limit) => {
    await expect(namer.search(query, limit)).resolves.toEqual([])
  })
})
